Tp2 ASyS ejercicio 2
Ignagx/Ingenieria-Electronica pull request #8
Opened 2024-08-24 20:30 UTC by McMoran2509

2024-08-24 21:09 UTC, ffpp2003 commented on ASyS/TP2/images/ej2.1.png
Usen colorcitos

2024-08-24 22:32 UTC, ffpp2003 commented on ASyS/TP2/tp2.tex
> +    \textbf{2) a)}
No hace falta agregar 2) a) para el punto. El 2) esta de mas, y el a) lo agrega automaticamente el LaTeX cada vez que pones \item

2024-08-24 22:33 UTC, ffpp2003 commented on ASyS/TP2/tp2.tex
> +    \textbf{Como}
Estaria bueno que haya algo de texto en caso de ser posible. Como alguna explicacion de lo que se va a hacer, con algun respaldo teorico

2024-08-24 22:33 UTC, ffpp2003 commented on ASyS/TP2/tp2.tex
> +    \textbf{Resolviendo la integral por sustitución}
comentario anterior

2024-08-24 22:33 UTC, ffpp2003 commented on ASyS/TP2/tp2.tex
> +    \textbf{Energía en el período:}
comentario anterior

2024-08-24 22:34 UTC, ffpp2003 requested changes
Hagan las correcciones

2024-08-25 16:26 UTC, Corte0 requested changes

2024-08-25 18:14 UTC, Corte0 requested changes

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +     Similarmente para la señal $x_2$.\\
Aca habria que dejar mas espacio sobre el titulo

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +       &=\frac{1}{4\pi j}\int^\pi_0 (1-e^{-j2t})dt=\frac{t|^\pi_0}{4\pi j}-\frac{e^{-2jt}|^\pi_0}{4\pi j (-2j)}\\
Ver los barrow

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +            \frac{1}{\pi(1-n^2)}, & n \text{ even} \\[5pt]
Esto habria que ponerlo en español

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +
Aca o pondria los c1 y -1 en el mismo entorno de alineacion o escribiria algo entre medio para que no se note tanto el salto

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +        x(t)=\frac{1}{\pi}+\frac{1}{2}sen(t)+\frac{2}{\pi}[\frac{1}{1-4}cos(2t)+\frac{1}{1-16}cos(4t)]
Los corchetes quedan chicos

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +			  I&=\frac{e^{j\omega t(n-m)}}{\omega(n-m)}|^{T_0}_0
El ultimo paso lo saltearía

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +	\textbf{Señal $x_2$}
Falta salto de linea

2024-08-25 18:14 UTC, Corte0 commented on ASyS/TP2/tp2.tex
> +	P_m=\sum^5_{-5}|C_n|^2=|\frac{1}{\pi}|^2+2|\frac{j}{4}|^2+2|-\frac{1}{3\pi}|^2+2|-\frac{1}{15\pi}|^2
Es inconsistente el uso del igual y el aproximado

2024-08-25 20:28 UTC, ffpp2003 commented on ASyS/TP2/images/ej2.2.png
este grafico no se va a ver un culo impreso

2024-08-25 20:29 UTC, ffpp2003 commented on ASyS/TP2/images/ej2.4.png
este tampoco se va a ver un culo. Usar la configuracion "imagen cuadrada", grosor de linea medio

2024-08-25 20:29 UTC, ffpp2003 commented on ASyS/TP2/images/ej2.6.png
este tampoco se va a ver un culo. Usar la configuracion "imagen cuadrada", grosor de linea medio

2024-08-25 20:31 UTC, ffpp2003 requested changes
corrijan los graficos

2024-08-25 22:04 UTC, Corte0 requested changes
Estas fotos estane  en muy mala calidad

2024-08-25 22:12 UTC, Corte0 requested changes

2024-08-25 22:57 UTC, fpp3 requested changes
fotoooos

2024-08-26 00:03 UTC, Corte0 commented on ASyS/TP2/images/ej.2.3.png
Estan al revez

2024-08-26 03:22 UTC, merged